# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"\x07\n\x05\x45mpty\"+\n\x05\x41\x63kID\x12\x10\n\x08sourceID\x18\x01 \x01(\t\x12\x10\n\x08targetID\x18\x02 \x01(\t\"\x19\n\x0bglobalAckID\x12\n\n\x02id\x18\x01 \x01(\t\"s\n\x0eportConstraint\x12\x10\n\x08sourceID\x18\x01 \x01(\t\x12\x10\n\x08targetID\x18\x02 \x01(\t\x12\r\n\x05round\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x10\n\x08\x62\x65havior\x18\x06 \x01(\t2\x9d\x01\n\tMessaging\x12\x1e\n\nAddAckByID\x12\x06.AckID\x1a\x06.Empty\"\x00\x12.\n\x11\x41\x64\x64PortConstraint\x12\x0f.portConstraint\x1a\x06.Empty\"\x00\x12&\n\x0c\x41\x64\x64GlobalAck\x12\x0c.globalAckID\x1a\x06.Empty\"\x00\x12\x18\n\x04ping\x12\x06.Empty\x1a\x06.Empty\"\x00\x62\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_ACKID = DESCRIPTOR.message_types_by_name['AckID']
_GLOBALACKID = DESCRIPTOR.message_types_by_name['globalAckID']
_PORTCONSTRAINT = DESCRIPTOR.message_types_by_name['portConstraint']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

AckID = _reflection.GeneratedProtocolMessageType('AckID', (_message.Message,), {
  'DESCRIPTOR' : _ACKID,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:AckID)
  })
_sym_db.RegisterMessage(AckID)

globalAckID = _reflection.GeneratedProtocolMessageType('globalAckID', (_message.Message,), {
  'DESCRIPTOR' : _GLOBALACKID,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:globalAckID)
  })
_sym_db.RegisterMessage(globalAckID)

portConstraint = _reflection.GeneratedProtocolMessageType('portConstraint', (_message.Message,), {
  'DESCRIPTOR' : _PORTCONSTRAINT,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:portConstraint)
  })
_sym_db.RegisterMessage(portConstraint)

_MESSAGING = DESCRIPTOR.services_by_name['Messaging']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=17
  _EMPTY._serialized_end=24
  _ACKID._serialized_start=26
  _ACKID._serialized_end=69
  _GLOBALACKID._serialized_start=71
  _GLOBALACKID._serialized_end=96
  _PORTCONSTRAINT._serialized_start=98
  _PORTCONSTRAINT._serialized_end=213
  _MESSAGING._serialized_start=216
  _MESSAGING._serialized_end=373
# @@protoc_insertion_point(module_scope)