# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: planner.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rplanner.proto\"\x07\n\x05\x45mpty\"+\n\x05\x41\x63kID\x12\x10\n\x08sourceID\x18\x01 \x01(\t\x12\x10\n\x08targetID\x18\x02 \x01(\t\"\x19\n\x0bglobalAckID\x12\n\n\x02id\x18\x01 \x01(\t\"s\n\x0eportConstraint\x12\x10\n\x08sourceID\x18\x01 \x01(\t\x12\x10\n\x08targetID\x18\x02 \x01(\t\x12\r\n\x05round\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x10\n\x08\x62\x65havior\x18\x06 \x01(\t2\x9d\x01\n\tMessaging\x12\x1e\n\nAddAckByID\x12\x06.AckID\x1a\x06.Empty\"\x00\x12.\n\x11\x41\x64\x64PortConstraint\x12\x0f.portConstraint\x1a\x06.Empty\"\x00\x12&\n\x0c\x41\x64\x64GlobalAck\x12\x0c.globalAckID\x1a\x06.Empty\"\x00\x12\x18\n\x04ping\x12\x06.Empty\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'planner_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=17
  _globals['_EMPTY']._serialized_end=24
  _globals['_ACKID']._serialized_start=26
  _globals['_ACKID']._serialized_end=69
  _globals['_GLOBALACKID']._serialized_start=71
  _globals['_GLOBALACKID']._serialized_end=96
  _globals['_PORTCONSTRAINT']._serialized_start=98
  _globals['_PORTCONSTRAINT']._serialized_end=213
  _globals['_MESSAGING']._serialized_start=216
  _globals['_MESSAGING']._serialized_end=373
# @@protoc_insertion_point(module_scope)
