# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from gossip.grpc import gossip_pb2 as gossip__pb2


class CostRegularGossipServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.add_message = channel.unary_unary(
                '/CostRegularGossipService/add_message',
                request_serializer=gossip__pb2.SyncSpec.SerializeToString,
                response_deserializer=gossip__pb2.Empty.FromString,
                )
        self.add_ack_success = channel.unary_unary(
                '/CostRegularGossipService/add_ack_success',
                request_serializer=gossip__pb2.AckSuccess.SerializeToString,
                response_deserializer=gossip__pb2.Empty.FromString,
                )
        self.add_ack_failure = channel.unary_unary(
                '/CostRegularGossipService/add_ack_failure',
                request_serializer=gossip__pb2.AckFailure.SerializeToString,
                response_deserializer=gossip__pb2.Empty.FromString,
                )
        self.add_global_ack_success = channel.unary_unary(
                '/CostRegularGossipService/add_global_ack_success',
                request_serializer=gossip__pb2.GlobalAckSuccess.SerializeToString,
                response_deserializer=gossip__pb2.Empty.FromString,
                )
        self.add_global_ack_failure = channel.unary_unary(
                '/CostRegularGossipService/add_global_ack_failure',
                request_serializer=gossip__pb2.GlobalAckFailure.SerializeToString,
                response_deserializer=gossip__pb2.Empty.FromString,
                )
        self.ping = channel.unary_unary(
                '/CostRegularGossipService/ping',
                request_serializer=gossip__pb2.Empty.SerializeToString,
                response_deserializer=gossip__pb2.Empty.FromString,
                )


class CostRegularGossipServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def add_message(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_ack_success(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_ack_failure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_global_ack_success(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_global_ack_failure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CostRegularGossipServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'add_message': grpc.unary_unary_rpc_method_handler(
                    servicer.add_message,
                    request_deserializer=gossip__pb2.SyncSpec.FromString,
                    response_serializer=gossip__pb2.Empty.SerializeToString,
            ),
            'add_ack_success': grpc.unary_unary_rpc_method_handler(
                    servicer.add_ack_success,
                    request_deserializer=gossip__pb2.AckSuccess.FromString,
                    response_serializer=gossip__pb2.Empty.SerializeToString,
            ),
            'add_ack_failure': grpc.unary_unary_rpc_method_handler(
                    servicer.add_ack_failure,
                    request_deserializer=gossip__pb2.AckFailure.FromString,
                    response_serializer=gossip__pb2.Empty.SerializeToString,
            ),
            'add_global_ack_success': grpc.unary_unary_rpc_method_handler(
                    servicer.add_global_ack_success,
                    request_deserializer=gossip__pb2.GlobalAckSuccess.FromString,
                    response_serializer=gossip__pb2.Empty.SerializeToString,
            ),
            'add_global_ack_failure': grpc.unary_unary_rpc_method_handler(
                    servicer.add_global_ack_failure,
                    request_deserializer=gossip__pb2.GlobalAckFailure.FromString,
                    response_serializer=gossip__pb2.Empty.SerializeToString,
            ),
            'ping': grpc.unary_unary_rpc_method_handler(
                    servicer.ping,
                    request_deserializer=gossip__pb2.Empty.FromString,
                    response_serializer=gossip__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CostRegularGossipService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CostRegularGossipService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def add_message(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CostRegularGossipService/add_message',
            gossip__pb2.SyncSpec.SerializeToString,
            gossip__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def add_ack_success(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CostRegularGossipService/add_ack_success',
            gossip__pb2.AckSuccess.SerializeToString,
            gossip__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def add_ack_failure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CostRegularGossipService/add_ack_failure',
            gossip__pb2.AckFailure.SerializeToString,
            gossip__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def add_global_ack_success(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CostRegularGossipService/add_global_ack_success',
            gossip__pb2.GlobalAckSuccess.SerializeToString,
            gossip__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def add_global_ack_failure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CostRegularGossipService/add_global_ack_failure',
            gossip__pb2.GlobalAckFailure.SerializeToString,
            gossip__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CostRegularGossipService/ping',
            gossip__pb2.Empty.SerializeToString,
            gossip__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
