# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgateway.proto\"\x07\n\x05\x45mpty\"\x17\n\x04Pong\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x17\n\x04\x44one\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"J\n\x08PortGoal\x12\x11\n\tcomponent\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x08\x12\r\n\x05\x66inal\x18\x04 \x01(\x08\"B\n\x0c\x42\x65haviorGoal\x12\x11\n\tcomponent\x18\x01 \x01(\t\x12\x10\n\x08\x62\x65havior\x18\x02 \x01(\t\x12\r\n\x05\x66inal\x18\x03 \x01(\x08\x32\x97\x01\n\tMessaging\x12\x17\n\x04ping\x12\x06.Empty\x1a\x05.Pong\"\x00\x12%\n\x0c\x61\x64\x64PortGoals\x12\t.PortGoal\x1a\x06.Empty\"\x00(\x01\x12-\n\x10\x61\x64\x64\x42\x65haviorGoals\x12\r.BehaviorGoal\x1a\x06.Empty\"\x00(\x01\x12\x1b\n\x08validate\x12\x05.Done\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=17
  _globals['_EMPTY']._serialized_end=24
  _globals['_PONG']._serialized_start=26
  _globals['_PONG']._serialized_end=49
  _globals['_DONE']._serialized_start=51
  _globals['_DONE']._serialized_end=74
  _globals['_PORTGOAL']._serialized_start=76
  _globals['_PORTGOAL']._serialized_end=150
  _globals['_BEHAVIORGOAL']._serialized_start=152
  _globals['_BEHAVIORGOAL']._serialized_end=218
  _globals['_MESSAGING']._serialized_start=221
  _globals['_MESSAGING']._serialized_end=372
# @@protoc_insertion_point(module_scope)
