# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from koda.grpc import gossip_pb2 as gossip__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gossip_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CostRegularGossipServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.add_message = channel.unary_unary(
                '/CostRegularGossipService/add_message',
                request_serializer=gossip__pb2.SyncSpec.SerializeToString,
                response_deserializer=gossip__pb2.Empty.FromString,
                _registered_method=True)
        self.add_config = channel.unary_unary(
                '/CostRegularGossipService/add_config',
                request_serializer=gossip__pb2.ConfigValue.SerializeToString,
                response_deserializer=gossip__pb2.Empty.FromString,
                _registered_method=True)
        self.add_ack_success = channel.unary_unary(
                '/CostRegularGossipService/add_ack_success',
                request_serializer=gossip__pb2.AckSuccess.SerializeToString,
                response_deserializer=gossip__pb2.Empty.FromString,
                _registered_method=True)
        self.add_ack_failure = channel.unary_unary(
                '/CostRegularGossipService/add_ack_failure',
                request_serializer=gossip__pb2.AckFailure.SerializeToString,
                response_deserializer=gossip__pb2.Empty.FromString,
                _registered_method=True)
        self.add_conf_success = channel.unary_unary(
                '/CostRegularGossipService/add_conf_success',
                request_serializer=gossip__pb2.ConfSuccess.SerializeToString,
                response_deserializer=gossip__pb2.Empty.FromString,
                _registered_method=True)
        self.add_conf_failure = channel.unary_unary(
                '/CostRegularGossipService/add_conf_failure',
                request_serializer=gossip__pb2.ConfFailure.SerializeToString,
                response_deserializer=gossip__pb2.Empty.FromString,
                _registered_method=True)
        self.add_global_ack_success = channel.unary_unary(
                '/CostRegularGossipService/add_global_ack_success',
                request_serializer=gossip__pb2.GlobalAckSuccess.SerializeToString,
                response_deserializer=gossip__pb2.Empty.FromString,
                _registered_method=True)
        self.add_global_ack_failure = channel.unary_unary(
                '/CostRegularGossipService/add_global_ack_failure',
                request_serializer=gossip__pb2.GlobalAckFailure.SerializeToString,
                response_deserializer=gossip__pb2.Empty.FromString,
                _registered_method=True)
        self.ping = channel.unary_unary(
                '/CostRegularGossipService/ping',
                request_serializer=gossip__pb2.Empty.SerializeToString,
                response_deserializer=gossip__pb2.Empty.FromString,
                _registered_method=True)


class CostRegularGossipServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def add_message(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_config(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_ack_success(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_ack_failure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_conf_success(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_conf_failure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_global_ack_success(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_global_ack_failure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CostRegularGossipServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'add_message': grpc.unary_unary_rpc_method_handler(
                    servicer.add_message,
                    request_deserializer=gossip__pb2.SyncSpec.FromString,
                    response_serializer=gossip__pb2.Empty.SerializeToString,
            ),
            'add_config': grpc.unary_unary_rpc_method_handler(
                    servicer.add_config,
                    request_deserializer=gossip__pb2.ConfigValue.FromString,
                    response_serializer=gossip__pb2.Empty.SerializeToString,
            ),
            'add_ack_success': grpc.unary_unary_rpc_method_handler(
                    servicer.add_ack_success,
                    request_deserializer=gossip__pb2.AckSuccess.FromString,
                    response_serializer=gossip__pb2.Empty.SerializeToString,
            ),
            'add_ack_failure': grpc.unary_unary_rpc_method_handler(
                    servicer.add_ack_failure,
                    request_deserializer=gossip__pb2.AckFailure.FromString,
                    response_serializer=gossip__pb2.Empty.SerializeToString,
            ),
            'add_conf_success': grpc.unary_unary_rpc_method_handler(
                    servicer.add_conf_success,
                    request_deserializer=gossip__pb2.ConfSuccess.FromString,
                    response_serializer=gossip__pb2.Empty.SerializeToString,
            ),
            'add_conf_failure': grpc.unary_unary_rpc_method_handler(
                    servicer.add_conf_failure,
                    request_deserializer=gossip__pb2.ConfFailure.FromString,
                    response_serializer=gossip__pb2.Empty.SerializeToString,
            ),
            'add_global_ack_success': grpc.unary_unary_rpc_method_handler(
                    servicer.add_global_ack_success,
                    request_deserializer=gossip__pb2.GlobalAckSuccess.FromString,
                    response_serializer=gossip__pb2.Empty.SerializeToString,
            ),
            'add_global_ack_failure': grpc.unary_unary_rpc_method_handler(
                    servicer.add_global_ack_failure,
                    request_deserializer=gossip__pb2.GlobalAckFailure.FromString,
                    response_serializer=gossip__pb2.Empty.SerializeToString,
            ),
            'ping': grpc.unary_unary_rpc_method_handler(
                    servicer.ping,
                    request_deserializer=gossip__pb2.Empty.FromString,
                    response_serializer=gossip__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CostRegularGossipService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CostRegularGossipService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CostRegularGossipService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def add_message(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CostRegularGossipService/add_message',
            gossip__pb2.SyncSpec.SerializeToString,
            gossip__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def add_config(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CostRegularGossipService/add_config',
            gossip__pb2.ConfigValue.SerializeToString,
            gossip__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def add_ack_success(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CostRegularGossipService/add_ack_success',
            gossip__pb2.AckSuccess.SerializeToString,
            gossip__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def add_ack_failure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CostRegularGossipService/add_ack_failure',
            gossip__pb2.AckFailure.SerializeToString,
            gossip__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def add_conf_success(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CostRegularGossipService/add_conf_success',
            gossip__pb2.ConfSuccess.SerializeToString,
            gossip__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def add_conf_failure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CostRegularGossipService/add_conf_failure',
            gossip__pb2.ConfFailure.SerializeToString,
            gossip__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def add_global_ack_success(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CostRegularGossipService/add_global_ack_success',
            gossip__pb2.GlobalAckSuccess.SerializeToString,
            gossip__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def add_global_ack_failure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CostRegularGossipService/add_global_ack_failure',
            gossip__pb2.GlobalAckFailure.SerializeToString,
            gossip__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CostRegularGossipService/ping',
            gossip__pb2.Empty.SerializeToString,
            gossip__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
